# Generated by Django 3.1 on 2020-09-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='penjualan1m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(verbose_name='')),
                ('barang', models.CharField(max_length=200)),
                ('kuantitas', models.IntegerField(default=0)),
                ('jumlah', models.BooleanField(max_length=10)),
                ('catatan', models.TextField(default='')),
            ],
        ),
    ]
