# Generated by Django 3.1 on 2020-09-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pem_kreditm',
            name='catatan',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pem_lainm',
            name='catatan',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pem_tunaim',
            name='catatan',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pembayaran_biayam',
            name='catatan',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pembayaran_lainm',
            name='catatan',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pend_lainm',
            name='catatan',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='penjualan2m',
            name='catatan',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='penjualan3m',
            name='catatan',
            field=models.CharField(max_length=200),
        ),
    ]
