# Generated by Django 3.1 on 2020-10-01 07:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penjualan2m',
            name='jatuh_tempo',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
