# Generated by Django 3.1 on 2020-10-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penjualan2m',
            name='barang',
        ),
        migrations.DeleteModel(
            name='penjualan3m',
        ),
        migrations.RenameField(
            model_name='pend_lainm',
            old_name='piutang',
            new_name='kas_masuk',
        ),
        migrations.RenameField(
            model_name='pend_lainm',
            old_name='jumlah',
            new_name='pendapatan',
        ),
        migrations.RemoveField(
            model_name='pend_lainm',
            name='catatan',
        ),
        migrations.DeleteModel(
            name='penjualan2m',
        ),
    ]
