# Generated by Django 3.1 on 2020-09-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualan1m',
            name='jumlah',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='penjualan1m',
            name='kuantitas',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='penjualan1m',
            name='tanggal',
            field=models.DateField(auto_now_add=True),
        ),
    ]
