# Generated by Django 3.1 on 2020-09-21 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0019_merge_20200921_0205'),
    ]

    operations = [
        migrations.DeleteModel(
            name='saldom',
        ),
        migrations.RemoveField(
            model_name='barangm',
            name='saldo_awal',
        ),
        migrations.RemoveField(
            model_name='penjualan2m',
            name='diterima',
        ),
    ]
