# Generated by Django 3.1 on 2020-09-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0020_auto_20200921_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penjualan1m',
            name='catatan',
            field=models.TextField(default='Pass'),
        ),
    ]
