# Generated by Django 3.1 on 2020-09-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0022_auto_20200921_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utangm',
            name='keterangan',
        ),
        migrations.AlterField(
            model_name='penjualan2m',
            name='terima',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='utangm',
            name='catatan',
            field=models.CharField(max_length=200),
        ),
    ]
