# Generated by Django 3.1 on 2020-09-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0023_auto_20200921_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran_lainm',
            name='dibayar',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
