# Generated by Django 3.1 on 2020-09-22 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0025_auto_20200922_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pembayaran_lainm',
            name='dibayar3',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
