# Generated by Django 3.1 on 2020-09-22 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0026_auto_20200922_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pembayaran_lainm',
            name='dibayar3',
        ),
    ]
