# Generated by Django 3.1 on 2020-09-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0027_remove_pembayaran_lainm_dibayar3'),
    ]

    operations = [
        migrations.AddField(
            model_name='pembayaran_lainm',
            name='dibayar3',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
