# Generated by Django 3.1 on 2020-09-30 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olshop', '0005_auto_20200929_0323'),
        ('olshop', '0028_pembayaran_lainm_dibayar3'),
        ('olshop', '0002_auto_20200924_0647'),
    ]

    operations = [
    ]
