# Generated by Django 3.1 on 2020-09-11 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='supplier',
            new_name='item_supplier',
        ),
    ]
