# Generated by Django 3.1 on 2020-09-08 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20200908_0303'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customeraddress',
            new_name='customer_address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customercontact',
            new_name='customer_contact',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='customername',
            new_name='customer_name',
        ),
    ]
