# Generated by Django 3.1 on 2020-09-08 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_auto_20200908_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplieraddress',
            new_name='supplier_address',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='suppliercontact',
            new_name='supplier_contact',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='suppliername',
            new_name='supplier_name',
        ),
    ]
