# Generated by Django 3.1 on 2020-09-08 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20200908_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(max_length=100),
        ),
    ]
