# Generated by Django 3.1 on 2020-09-08 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20200908_0340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='itemname',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemprice',
            new_name='item_saleprice',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='itemsaleprice',
            new_name='itemp_rice',
        ),
    ]
