# Generated by Django 3.1 on 2020-09-08 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0010_auto_20200908_0402'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_saleprice',
            new_name='item_sale_price',
        ),
    ]
