# Generated by Django 3.1 on 2020-09-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0011_auto_20200908_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemp_rice',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
