# Generated by Django 3.1 on 2020-10-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_item_itemsaleprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
