# Generated by Django 3.1 on 2020-10-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='phone1',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
