# Generated by Django 3.1 on 2020-10-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_auto_20201020_0637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone1',
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.TextField(default=None),
        ),
    ]
